services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: expedicao-frontend
    ports:
      - "${FRONTEND_PORT:-5772}:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: expedicao-backend
    ports:
      - "2515:2515"
    env_file:
      - ./backend/.env
